# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

before_install:
    - tlmgr install scheme-full
    - sudo apt-get install texlive-fonts-extra
language: R
cache: packages
branches:
  only:
  - travis_check
r_build_args: '--resave-data --compact-vignettes="both" '
