## Increasing coverage of spray_ops.R 

test_that("test suite aab",{
    S <- rspray(9)
    expect_error(!S)
    expect_true(+S == S)
    expect_error(S&S)
    expect_silent(jj <- 4*S)
    expect_silent(jj <- S*4)
    expect_silent(jj <- 4+S)
    expect_silent(jj <- S+4)
    expect_silent(jj <- S/4)
    expect_silent(jj <- -(S*0))
    expect_silent(jj <- -(0*S))
    expect_silent(jj <- S*(0*S))
    expect_silent(jj <- S*(S*0))
    expect_silent(jj <- (0*S)*S)
    expect_silent(jj <- (0*S)*S)
    expect_true(S != S+3)
    expect_true(S != 3+S)
    expect_error(4/S)
    expect_error(S^S)
    expect_error(S^(-9))
    expect_error(S == 6)
    expect_true(S == S + (S*0))
    expect_true(S == (S*0) + S)
    expect_error(S != 6)
    expect_false(rspray(4,arity=3) == rspray(8,arity=4))
    expect_false(1000+rspray(4,arity=3) == rspray(28,arity=3))

})

